### ISSUE TITLE
Feature suggestion: Some kind of report of what was done

### ISSUE THREAD

**Issue by mudrd8mz** [vadimonus/moodle-local_questionbulkupdate#1]
It would be nice if the plugin provided a list of questions it processed with a confirmation of the performed change. It would allow users to stay assured they did everything right.

**Comment by vadimonus** [comment]
@mudrd8mz, please clarify. You whant to see confirmation dialog with questions list before processing, or list of processed questions with changes log after processing?
How should it look? Should unchanged questions be included? Should changes be shown or just question names?

**Comment by mudrd8mz** [comment]
Those all are really good questions :-)

Look, my whole point was to share this as a general user experience principle. When there is a form where the user can configure some parameters of an action, and a button to execute that action, is pressed, then the user should get _some_ feedback. It may be as simple as a message "Questions were edited" or it can be a detailed report of what changes were made, or a mix of both etc. It's up to you, I am not the product owner here.

I only wanted to share that it was not a good user experience for me to press button and be simply redirected back to the default (different) screen within the question bank, without any feedback at all. Just that.

It's a detail for sure.

**Comment by vadimonus** [comment]
Added \core\notification::success message after processing
