### ISSUE TITLE
Cannot use plugin after installation

### ISSUE THREAD

**Issue by SixStrings89** [vadimonus/moodle-local_questionbulkupdate#2]
Hi

I've just installed the local-questionbulkupdate on our moodle 3.6.4 and i've got the following error:
![quickform](https://user-images.githubusercontent.com/28749382/121695185-1be38700-cacb-11eb-8606-0db4db50ba46.png)

The error says: Error: Call to undefined method HTML_QuickForm_Error::onQuickFormEvent(). Is moodle 3.6.4 (against the information on the plugin page) currently supported?

What can i do to solve the error?

Thanks and Best

**Comment by vadimonus** [comment]
Sorry for not answering for so long. Fixed, please install latest version
