### ISSUE TITLE
Moodle 4 support

### ISSUE THREAD

**Issue by acquaalta** [vadimonus/moodle-local_questionbulkupdate#3]
Hi,
Could you please add support for Moodle 4?
Even if the current version of the plugin would work on Moodle 4, an official support would be great.

Thanks even for considering it :-)

**Comment by vadimonus** [comment]
@acquaalta 
If you are using classic theme, you may see current version works with 4.0. But with default theme it's not functional, so i can not mark 4.0 as supported.

I'm waiting for fixes in https://tracker.moodle.org/browse/MDL-75347 and https://tracker.moodle.org/browse/MDL-74615. After that plugins will be rewritten from local_ to qbank_.

Next time you may ask such questions as comment in moodle plugins directory, without creating issue on github
